Models/ApiModels/League.cs
using R6MIX.Models.ApiModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace R6MIX.Models
{
    public class League
    {
        public int id { get; set; }
        public string image_url { get; set; }
        public DateTime modified_at { get; set; }
        public string name { get; set; }
        public List<Series> series { get; set; }
        public string slug { get; set; }
        public string url { get; set; }
        public Videogame videogame { get; set; }
    }
}

Models/ApiModels/Series.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace R6MIX.Models.ApiModels
{
    public class Series
    {
        public DateTime begin_at { get; set; }
        public object description { get; set; }
        public DateTime end_at { get; set; }
        public string full_name { get; set; }
        public int id { get; set; }
        public int league_id { get; set; }
        public DateTime modified_at { get; set; }
        public string name { get; set; }
        public string season { get; set; }
        public string slug { get; set; }
        public string tier { get; set; }
        public object winner_id { get; set; }
        public object winner_type { get; set; }
        public int year { get; set; }
    }
}

Controllers/ESportAPIController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using R6MIX.Models;
using R6MIX.Models.ApiModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace R6MIX.Controllers
{
    public class ESportAPIController : Controller
    {
        private static string Token = "W4sBPkh2FWLjMAZEcLi8dxkZJ2PjL8Je5U_xLzlXksqeI517zW8";
        private static string TokenAsQuery = "token=" + Token;
        private static string ApiBaseUrl = "https://api.pandascore.co/r6siege/";
        public async Task<IActionResult> Index()
        {
            List<League> leagues = new List<League>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(ApiBaseUrl + "leagues?" + TokenAsQuery))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    leagues = JsonConvert.DeserializeObject<List<League>>(apiResponse,
                            new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore });
                }
            }
            return View(leagues);
        }

        public async Task<IActionResult> League(int? id) {
            if (id == null)
            {
                return NotFound();
            }

            List<League> leagues = new List<League>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(ApiBaseUrl + "leagues?" + TokenAsQuery))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    leagues = JsonConvert.DeserializeObject<List<League>>(apiResponse,
                            new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore });
                }
            }
            return View(leagues.First(m => m.id == id));
        }

        public async Task<IActionResult> Serie(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            List<Series> serie = new List<Series>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(ApiBaseUrl + "series?" + TokenAsQuery))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    serie = JsonConvert.DeserializeObject<List<Series>>(apiResponse,
                            new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore });
                }
            }
            return View(serie.First(m => m.id == id));
        }

        public async Task<IActionResult> AllPlayers()
        {
            List<Player> players = new List<Player>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(ApiBaseUrl + "players?" + TokenAsQuery))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    players = JsonConvert.DeserializeObject<List<Player>>(apiResponse);
                }
            }
            return View(players);
        }
    }
}

Views/ESportAPI/AllPlayers.cshtml
@model IEnumerable<R6MIX.Models.ApiModels.Player>

@{
    ViewData["Title"] = "Index";
}

<div class="text-center">
    <h1 class="display-4">Players</h1>
    @foreach (var item in Model)
    {
        <p>@item.first_name</p>
    }
</div>

Views/ESportAPI/Index.cshtml
@model IEnumerable<R6MIX.Models.League>

@{
    ViewData["Title"] = "Index";
}

<div class="text-center">
    <h1 class="display-4">Leagues</h1>
    <div class="d-flex align-items-end justify-content-center row">
        @foreach (var item in Model)
        {
            <div class="col-2 pb-3">
                <div class="card bg-dark border-0 mb-3">
                    <div class="  d-flex justify-content-center pb-2">
                        <img class="card-img-top" src="@item.image_url" alt="League image" style="width: 100px; height: auto;">
                    </div>
                    <div class="card-body bg-grey text-dark py-2">
                        <a class="stretched-link nav-link py-1" asp-controller="ESportAPI" asp-action="League" asp-route-id="@item.id">
                            <h5 class="font-weight-bold">@item.name</h5>
                        </a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Views/ESportAPI/League.cshtml
@model R6MIX.Models.League

@{
    ViewData["Title"] = "League";
}

<div class="text-center">
    <h1 class="display-4 font-italic">@Model.name</h1>
    <div class="d-flex align-items-end justify-content-center row">
        <div class="bg-dark  d-flex justify-content-center pb-2">
            <img class="card-img-top" src="@Model.image_url" alt="League image" style="width: 100px; height: auto;">
        </div>
    </div>
</div>
<div>
    @if (Model.series != null)
    {
        foreach (var serie in Model.series)
        {
            <hr class="m-0 ml-2 mb-3" style="background-color: white; height: 1px;" />
            @if (serie.description != null) { <p>Description: @serie.description</p> }
            @if (serie.full_name != null) { <p>Name: @serie.full_name</p> }
            @if (serie.begin_at != null) { <p>Begins At: @serie.begin_at</p> }
            @if (serie.end_at != null) { <p>Ends At: @serie.end_at</p> }
            @if (serie.season != null) { <p>Season: @serie.season</p> }
            @if (serie.year != null) { <p>Year: @serie.year</p> }
            @if (serie.tier != null) { <p>Tier: @serie.tier</p> }
            @*@if (serie.id != null) { 
                <a class="btn btn-sm btn-dark" asp-controller="ESportAPI" asp-action="Serie" asp-route-id="@serie.id">
                    Click Here To Know More
                </a> 
                }*@
        }
    }
</div>

Views/ESportAPI/Serie.cshtml
@model R6MIX.Models.ApiModels.Series

@{
    ViewData["Title"] = "Serie";
}

<div class="text-center">
    <h1 class="display-4 font-italic">@Model.name</h1>
    <p>
        @Model.begin_at
    </p>
</div>
<div>
</div>